[package]
name = "elicitation_derive"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

description = "Derive macros for elicitation library"
keywords = ["mcp", "derive", "macro", "elicitation"]
categories = ["development-tools"]

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
elicitation = { path = "../elicitation" }
tracing = { workspace = true }
